"""Bronze layer data model: table schemas and ID/reference tables.

Schemas mirror the historical Ergast CSV columns so API rows can be merged
into the same structure.
"""

# Bronze table schemas (historical CSV columns, in historical order)
SCHEMAS = {
    "seasons": ["year", "url"],
    "status": ["statusId", "status"],
    "circuits": [
        "circuitId",
        "circuitRef",
        "name",
        "location",
        "country",
        "lat",
        "lng",
        "alt",
        "url",
    ],
    "drivers": [
        "driverId",
        "driverRef",
        "number",
        "code",
        "forename",
        "surname",
        "dob",
        "nationality",
        "url",
    ],
    "constructors": ["constructorId", "constructorRef", "name", "nationality", "url"],
    "races": [
        "raceId",
        "year",
        "round",
        "circuitId",
        "name",
        "date",
        "time",
        "url",
        "fp1_date",
        "fp1_time",
        "fp2_date",
        "fp2_time",
        "fp3_date",
        "fp3_time",
        "quali_date",
        "quali_time",
        "sprint_date",
        "sprint_time",
    ],
    "results": [
        "resultId",
        "raceId",
        "driverId",
        "constructorId",
        "number",
        "grid",
        "position",
        "positionText",
        "positionOrder",
        "points",
        "laps",
        "time",
        "milliseconds",
        "fastestLap",
        "rank",
        "fastestLapTime",
        "fastestLapSpeed",
        "statusId",
    ],
    "qualifying": [
        "qualifyId",
        "raceId",
        "driverId",
        "constructorId",
        "number",
        "position",
        "q1",
        "q2",
        "q3",
    ],
    "sprint_results": [
        "sprintResultId",
        "raceId",
        "driverId",
        "constructorId",
        "number",
        "grid",
        "position",
        "positionText",
        "positionOrder",
        "points",
        "laps",
        "time",
        "milliseconds",
        "fastestLap",
        "fastestLapTime",
        "statusId",
    ],
    "lap_times": ["raceId", "driverId", "lap", "position", "time", "milliseconds"],
    "pit_stops": [
        "raceId",
        "driverId",
        "stop",
        "lap",
        "time",
        "duration",
        "milliseconds",
    ],
    "driver_standings": [
        "driverStandingsId",
        "raceId",
        "driverId",
        "points",
        "position",
        "positionText",
        "wins",
    ],
    "constructor_standings": [
        "constructorStandingsId",
        "raceId",
        "constructorId",
        "points",
        "position",
        "positionText",
        "wins",
    ],
}

# Tables whose surrogate IDs are allocated for new API rows
ID_TABLES = {
    "circuits": "circuitId",
    "drivers": "driverId",
    "constructors": "constructorId",
    "status": "statusId",
    "races": "raceId",
    "results": "resultId",
    "qualifying": "qualifyId",
    "sprint_results": "sprintResultId",
    "driver_standings": "driverStandingsId",
    "constructor_standings": "constructorStandingsId",
}

# Slug/reference tables used to resolve API references to historical IDs
SLUG_TABLES = {
    "drivers": ("driverRef", "driverId"),
    "circuits": ("circuitRef", "circuitId"),
    "constructors": ("constructorRef", "constructorId"),
    "status": ("status", "statusId"),
}
